set -e
source activate surv_pred
bash /home/Guanjq/NewWork/MedAlignFusion/TrainScripts/tcga_lusc/run015_medkgat_fusion_qwen_data_medk.sh
bash /home/Guanjq/NewWork/MedAlignFusion/TrainScripts/tcga_lusc/run016_medkgat_fusion_qwen_data_medk.sh
bash /home/Guanjq/NewWork/MedAlignFusion/TrainScripts/tcga_lusc/run017_medkgat_fusion_ctab_qwen_data_medk.sh