source activate medfusion
bash /home/Guanjq/NewWork/MedAlignFusion/TrainScripts/oscc_inhouse/run009_only_report_pathology.sh
bash /home/Guanjq/NewWork/MedAlignFusion/TrainScripts/oscc_inhouse/run012_image_text_pathology.sh